### ISSUE TITLE
Move KubernetesWrapper to new repository

### ISSUE THREAD

**Issue by tjololo** [Altinn/app-kubernetes-wrapper#1]
### Description

KubernetesWrapper still resides in altinn-studio repo. Most of the code is now separated into smaller repos.

The source code for kuberneteswrapepr should be moved to app-kubernetes-wrapper repository

### Tasks

- [x] Move source code and git history to new repository
- [x] Update release pipelines to fetch the source from the new repository
- [x] Create actions for kuberneteswrapper repository
- [x] Setup codeQL and other integrations
